jar = 'jars/hello_world.jar'

class_loads = [ 'java.lang.String', 'java.util.IdentityHashMap' ]

[[methods]]
name = '<init>'
class = 'java.lang.String'

[[methods]]
name = '<init>'
class = 'java.lang.Thread'
