[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
ipc-channel = { workspace = true }
shared = { version = "0.1.0", path = "../shared" }
chrono = { workspace = true }
